openapi: 3.0.3
info:
  title: Griot and Grits - Stories API
  version: 1.0.0
  description: API endpoints for story management and discovery feed

paths:
  /stories:
    get:
      summary: List stories (discovery feed or user's stories)
      parameters:
        - name: cursor
          in: query
          schema:
            type: string
          description: Pagination cursor
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: privacy
          in: query
          schema:
            type: string
            enum: [public, family_only, private, all]
          description: Filter by privacy (default public for discovery feed)
        - name: sort
          in: query
          schema:
            type: string
            enum: [recent, for_you]
            default: recent
        - name: fields
          in: query
          schema:
            type: string
          description: Comma-separated list of fields to return
        - name: since
          in: query
          schema:
            type: string
            format: date-time
          description: For incremental sync
      responses:
        '200':
          description: List of stories
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Story'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
    post:
      summary: Create a new story
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title]
              properties:
                title:
                  type: string
                description:
                  type: string
                privacy:
                  type: string
                  enum: [public, family_only, private]
                  default: public
                quality:
                  type: string
                  enum: ['240p', '480p', '720p', '1080p']
                duration_seconds:
                  type: integer
                location:
                  $ref: '#/components/schemas/LocationInput'
      responses:
        '201':
          description: Story created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Story'

  /stories/{id}:
    get:
      summary: Get story by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: fields
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Story details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Story'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      summary: Update story
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: If-Match
          in: header
          schema:
            type: string
          description: ETag for conflict detection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                privacy:
                  type: string
                  enum: [public, family_only, private]
      responses:
        '200':
          description: Story updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Story'
        '409':
          $ref: '#/components/responses/Conflict'

    delete:
      summary: Delete story
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Story deleted

  /stories/{id}/full:
    get:
      summary: Get story with all nested data (composite endpoint)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Story with attachments, location, metadata
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Story'
                  - type: object
                    properties:
                      attachments:
                        type: array
                        items:
                          $ref: '#/components/schemas/Attachment'
                      location:
                        $ref: '#/components/schemas/Location'
                      family_members:
                        type: array
                        items:
                          $ref: '#/components/schemas/FamilyTreeMemberBasic'

  /stories/{id}/like:
    post:
      summary: Like a story
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Story liked
    delete:
      summary: Unlike a story
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Like removed

  /stories/{id}/favorite:
    post:
      summary: Add story to favorites
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Story favorited
    delete:
      summary: Remove from favorites
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Favorite removed

  /stories/{id}/report:
    post:
      summary: Report inappropriate content
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [reason]
              properties:
                reason:
                  type: string
                  enum: [spam, harassment, inappropriate, other]
                reason_details:
                  type: string
      responses:
        '201':
          description: Report submitted
          content:
            application/json:
              schema:
                type: object
                properties:
                  tracking_id:
                    type: string

components:
  schemas:
    Story:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        title:
          type: string
        description:
          type: string
        video_url:
          type: string
        thumbnail_url:
          type: string
        duration_seconds:
          type: integer
        quality:
          type: string
          enum: ['240p', '480p', '720p', '1080p']
        privacy:
          type: string
          enum: [public, family_only, private]
        is_auto_privated:
          type: boolean
        processing_status:
          type: string
          enum: [pending, processing, completed, failed]
        ai_metadata:
          type: object
          properties:
            tags:
              type: array
              items:
                type: string
            people:
              type: array
              items:
                type: string
            places:
              type: array
              items:
                type: string
            topics:
              type: array
              items:
                type: string
        like_count:
          type: integer
        is_favorited_by_user:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        etag:
          type: string

    Attachment:
      type: object
      properties:
        id:
          type: string
        file_url:
          type: string
        file_type:
          type: string
          enum: [photo, video, document]
        timestamp_seconds:
          type: integer
        display_order:
          type: integer

    Location:
      type: object
      properties:
        id:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        place_name:
          type: string
        city:
          type: string
        state:
          type: string

    LocationInput:
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number
        place_name:
          type: string
        source:
          type: string
          enum: [gps, manual]

    FamilyTreeMemberBasic:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

    Pagination:
      type: object
      properties:
        next_cursor:
          type: string
        has_more:
          type: boolean

  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: NOT_FOUND
                  message:
                    type: string

    Conflict:
      description: Version conflict
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: CONFLICT
                  message:
                    type: string
                  current_version:
                    $ref: '#/components/schemas/Story'
